### Import numpy library  

In [11]:
import numpy as np

### Create an Array using array function  

In [ ]:
ar = np.array([1,2,3])
ar

array([1, 2, 3])

### Create an Array containing numbers from 20 to 40 

In [ ]:
ar = np.array(range(20,41))
ar

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36,
       37, 38, 39, 40])

### Create an array which contain 10 elements and every element is 5  

In [ ]:
ar = np.ones(10)*5
ar

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

### create a 1-d array and then convert it into 3-d array  

In [ ]:
ar = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18])
ar2 = ar.reshape(2,3,3)
ar2

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

### Create 2-d array which contains random 25 numbers between 0 and 1 

In [ ]:
ar = np.random.rand(5,5)
print(ar)

[[0.17511778 0.89131473 0.53327408 0.13262619 0.82872635]
 [0.96478237 0.32756432 0.68054912 0.51949849 0.98544637]
 [0.48344349 0.19069068 0.50476651 0.62079723 0.75129497]
 [0.00755801 0.8969071  0.53457395 0.8664747  0.31037175]
 [0.96108101 0.68724705 0.63737435 0.05369129 0.66388007]]


### create array containing 20 random integer then replace every even number with -1 
#### Example - 
####                  array --- >  [44,55,12,6,3] 
####                  ouput ----> [-1,55, -1,-1,3]


In [ ]:
ar = np.random.randint(100,size=20)
print(ar)
ar2 = np.where(ar%2 == 0, -1, ar)
print(ar2)

[35  3 81 21  6 43 22 93 73 92 67 87 38 20  4 79 58 53 98 80]
[35  3 81 21 -1 43 -1 93 73 -1 67 87 -1 -1 -1 79 -1 53 -1 -1]


#### You have a matrix 
[[5 , 10, 15, 20, 25],
[30, 35, 40, 45, 50],
[55, 60, 65, 70, 75],
[80, 85, 90, 95, 100]]

Extract
[30,35,40]
[55, 60, 65]

In [ ]:
ar = np.array([[5 , 10, 15, 20, 25], [30, 35, 40, 45, 50], [55, 60, 65, 70, 75], [80, 85, 90, 95, 100]])
print(ar[1][:3])
print(ar[2][:3])

[30 35 40]
[55 60 65]


### Concatenate two 1-d array   

In [ ]:
ar = [1,2,3]
ar2 = [4,5,6]
ar+ar2

[1, 2, 3, 4, 5, 6]

### Stack 2-d matrix horizontally and vertically

In [13]:
a = np.array([[1,2,30],[10,15,4]])
b = np.array([[1,2,3],[12,19,29]])
print("Horizontal Stacking")
print(np.hstack((a,b)))
print("Vertical Stacking")
print(np.vstack((a,b)))

Horizontal Stacking
[[ 1  2 30  1  2  3]
 [10 15  4 12 19 29]]
Vertical Stacking
[[ 1  2 30]
 [10 15  4]
 [ 1  2  3]
 [12 19 29]]
